language: php

php:
  - hhvm
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'hhvm.jit = false' >> /etc/hhvm/php.ini ; fi
  - composer self-update --stable -n

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - vendor/phpunit/phpunit/phpunit --coverage-text
