language: php

php:
  - 8.1
  - 8.0
  - 7.4
  - 7.3
  - 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update --stable -n

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - bin/phpunit --coverage-text
